# Generated by Django 5.1.4 on 2025-01-04 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('ingest_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorpusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('summary', models.TextField()),
                ('scores', models.JSONField()),
                ('report', models.TextField()),
                ('review', models.TextField()),
                ('reviwer', models.CharField(max_length=100)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('num_chunks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('chunk_txt', models.TextField()),
                ('vector', models.JSONField()),
                ('chunk_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('scores', models.JSONField()),
                ('desc', models.TextField()),
                ('summary', models.TextField()),
                ('report', models.TextField()),
                ('review', models.TextField()),
                ('reviwer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.document')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('scores', models.JSONField()),
                ('summary', models.TextField()),
                ('report', models.TextField()),
                ('review', models.TextField()),
                ('reviewer', models.CharField(max_length=100)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.chunk')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_scores', to='ui.keyword')),
            ],
        ),
    ]
