# Generated by Django 5.1.4 on 2025-01-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpusreport',
            old_name='reviwer',
            new_name='reviewer',
        ),
    ]
