# Generated by Django 5.1.4 on 2025-01-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_rename_reviwer_corpusreport_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentreport',
            old_name='reviwer',
            new_name='reviewer',
        ),
    ]
